Hackwon_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('question/', include('cs.urls')),
    path('content/', include('content.urls')),
    path('blog/', include('blog.urls')),
    path('', index, name='index'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

content/urls.py
from django.urls import path
from .views import *

app_name = 'content'

urlpatterns = [
    path('', hackwon_in_category, name='hackwon_all'),
    path('detail/<int:pk>/', hackwon_detail, name='hackwon_detail'),
    path('category/<int:category_id>/', hackwon_in_category, name='hackwon_in_category'),
    path('vote/<int:hackwon_id>/', hackwon_vote, name='hackwon_vote'),
]

cs/urls.py
from django.urls import path
from .views import *

app_name = 'cs'

urlpatterns = [
    path('', question_list, name='question_list'),
    path('<int:question_id>/', question_detail, name='question_detail'),
    path('question/answer/create/<int:question_id>/', answer_create, name='answer_create'),
    path('answer/delete/<int:answer_id>/', answer_delete, name='answer_delete'),
    path('question/create/', question_create, name='question_create'),
    path('question/<int:question_id>/update/', question_update, name='question_update'),
    path('question/<int:question_id>/delete/', question_delete, name='question_delete'),
]

content/models.py
from django.db import models
from django.urls import reverse
import os
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=200, unique=True, verbose_name='course_category')
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('content:hackwon_in_category', args=[self.id])

class Hackwon(models.Model):
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, related_name='hackwons')
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)
    image = models.ImageField(upload_to='hackwons/%Y/%m/%d', blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    meta_description = models.TextField(blank=True, null=True)
    region = models.CharField(max_length=200, db_index=True, null=True)
    tuition = models.CharField(max_length=200, db_index=True, null=True)
    course = models.CharField(max_length=200, db_index=True, null=True)
    dormitory_available = models.BooleanField(default=True)
    phone_number = models.CharField(max_length=20, blank=True, null=True) 
    latitude = models.FloatField(null=True, blank=True)  # 위도
    longitude = models.FloatField(null=True, blank=True)  # 경도
    voter = models.ManyToManyField(User, related_name='voted_hackwons') # 좋아요기능

    class Meta:
        index_together = [['id', 'slug']]

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('content:hackwon_detail', args=[self.id])
    


    

content/views.py
from django.shortcuts import render, get_object_or_404
from .models import *
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.db.models import Q

# def index(request): # 메인페이지
#     return render(request, 'content/index.html')

def hackwon_in_category(request, category_id=None):
    current_category = None
    categories = Category.objects.all()
    query = request.GET.get("q", "")
    
    if query:
        hackwons = Hackwon.objects.filter(
            Q(name__icontains=query) | 
            Q(description__icontains=query) |
            Q(region__icontains=query) |
            Q(tuition__icontains=query) |
            Q(course__icontains=query) |
            Q(dormitory_available__icontains=query)
        )
    else:
        hackwons = Hackwon.objects.all()
    
    if category_id:
        current_category = get_object_or_404(Category, id=category_id)
        hackwons = hackwons.filter(category=current_category)

    return render(request, 'content/content.html', {
        'current_category': current_category, 
        'categories': categories, 
        'hackwons': hackwons
    })


def hackwon_detail(request, pk):
    hackwon = get_object_or_404(Hackwon, pk=pk)
    return render(request, 'content/content_detail.html', {'hackwon': hackwon})

# 좋아요 기능
@login_required
def hackwon_vote(request, hackwon_id):
    hackwon = get_object_or_404(Hackwon, pk=hackwon_id)
    if request.user in hackwon.voter.all():
        hackwon.voter.remove(request.user)  # 이미 추천했다면 추천 취소
        voted = False
    else:
        hackwon.voter.add(request.user)  # 추천하지 않았다면 추천 추가
        voted = True
    return JsonResponse({'voted': voted, 'total_votes': hackwon.voter.count()})

content/templates/content/content.html
{% extends 'base/base_with_navbar.html' %}
{% block title %}Category Page{% endblock %}
{% block content %}
<div class="row">
    <div class="col-2">
        <!-- Category Sidebar -->
        <div class="list-group">
            <a href="/" class="list-group-item {% if not current_category %}active{% endif %}">All</a>
            {% for c in categories %}
            <a href="{{ c.get_absolute_url }}" class="list-group-item {% if current_category.slug == c.slug %}active{% endif %}">{{ c.name }}</a>
            {% endfor %}
        </div>
    </div>
    <div class="col">
      <!-- 검색기능 -->
      <form method="get" action=".">
        <input type="text" name="q" placeholder="원하는 학원을 검색해보세요." value="{{ request.GET.q }}">
        <button type="submit">Search</button>
      </form>
      <!-- 검색기능 -->
        <!-- Category or All Hackwons Heading -->
        <div class="alert alert-info" role="alert">
            {% if current_category %}{{ current_category.name }}{% else %}All Hackwons{% endif %}
        </div>
        <div class="row">
            {% for hackwon in hackwons %}
            <div class="col-4">
                <div class="card">
                    {% if hackwon.image %}
                    <a href="{% url 'content:hackwon_detail' hackwon.id %}"><img class="card-img-top" src="{{ hackwon.image.url }}" alt="{{ hackwon.name }}"></a>
                    {% endif %}
                    <div class="card-body">
                        <!-- Hackwon Name as Link -->
                        <h5 class="card-title">
                            <a href="{% url 'content:hackwon_detail' hackwon.id %}">{{ hackwon.name }}</a>
                        </h5>
                        <!-- Hackwon Details -->
                        <p class="card-text">{{ hackwon.region }}</p>
                        <p class="badge badge-secondary">{{ hackwon.tuition }}원</p>
                        {% if hackwon.dormitory_available %}
                        <p class="card-text"><span class="badge badge-success">기숙사 있음</span></p>
                        {% endif %}
                        <button class="vote-btn" data-hackwon="{{ hackwon.id }}">추천 <span class="votes">{{ hackwon.voter.count }}</span></button>
                    </div>
                </div>
            </div>
            {% endfor %}          
<!-- 좋아요 기능 시작 -->
          <script>
            document.addEventListener("DOMContentLoaded", function() {
                document.querySelectorAll('.vote-btn').forEach(function(button) {
                    button.onclick = function() {
                        var hackwonId = this.dataset.hackwon;
                        var xhr = new XMLHttpRequest();
                        xhr.open("GET", "{% url 'content:hackwon_vote' 9999 %}".replace('9999', hackwonId), true);
                        xhr.setRequestHeader("X-Requested-With", "XMLHttpRequest");
                        xhr.onload = function() {
                            if (this.status == 200) {
                                var response = JSON.parse(this.responseText);
                                var votesSpan = button.querySelector('.votes');
                                votesSpan.textContent = response.total_votes;
                                if (response.voted) {
                                    button.classList.add('voted');
                                } else {
                                    button.classList.remove('voted');
                                }
                            }
                        };
                        xhr.send();
                    }
                });
            });
            </script>
            <!-- 좋아요 기능 끝 -->
          </div>
      </div>
        </div>
    </div>


{% endblock %}

content/templates/content/content_detail.html
{% extends 'base/base_with_navbar.html' %}
{% block title %}{{ hackwon.name }} Detail{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-4">
            {% if hackwon.image %}  <!-- 이미지가 있을 경우에만 표시 -->
                <img src="{{ hackwon.image.url }}" width="100%">
            {% endif %}
        </div>
        <div class="col">
            <h1 class="display-6">{{ hackwon.name }}</h1>
            <p><span class="badge badge-secondary">Region</span> {{ hackwon.region }}</p>
            <p><span class="badge badge-secondary">Tuition</span> {{ hackwon.tuition }}</p>
            <p><span class="badge badge-secondary">Course</span> {{ hackwon.course }}</p>
            {% if hackwon.dormitory_available %}
                <p><span class="badge badge-success">Dormitory Available</span></p>
            {% endif %}
            <!-- 전화번호 추가 -->
            {% if hackwon.phone_number %}
                <p><span class="badge badge-secondary">Phone Number</span> {{ hackwon.phone_number }}</p>
            {% endif %}
            <h5><span class="badge badge-secondary">Description</span>{{ hackwon.description|linebreaks }}</h5>
        </div>
    </div>
</div>
{% endblock %}

content/templates/content/index.html
{% extends 'base.html' %}

{% block title %}- Landing{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8 panel panel-default">
            <p>대문페이지</p>
        </div>
        <div class="col-md-2"></div>
    </div>
{% endblock %}