Hackwon_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('question/', include('cs.urls')),
    path('content/', include('content.urls')),
    path('blog/', include('blog.urls')),
    path('', index, name='index'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    path('', blog_list, name='blog_list'),
    path('detail/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('upload/', BlogUploadView.as_view(), name='blog_upload'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/like/<int:pk>/', blog_like, name='blog_like'),
]

cs/urls.py
from django.urls import path
from .views import *

app_name = 'cs'

urlpatterns = [
    path('', question_list, name='question_list'),
    path('<int:question_id>/', question_detail, name='question_detail'),
    path('question/answer/create/<int:question_id>/', answer_create, name='answer_create'),
    path('answer/delete/<int:answer_id>/', answer_delete, name='answer_delete'),
    path('question/create/', question_create, name='question_create'),
    path('question/<int:question_id>/update/', question_update, name='question_update'),
    path('question/<int:question_id>/delete/', question_delete, name='question_delete'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Blog(models.Model):
    author = models.ForeignKey(User,on_delete=models.SET_NULL, null=True, related_name='user_blogs')
    photo = models.ImageField(upload_to='photos/%Y/%m/%d', default='photos/no_image.png')
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    likes = models.ManyToManyField(User, related_name='blog_likes', blank=True)

    class Meta:
        ordering = ['-updated']

    def __str__(self):
        return self.author.username + " " + self.created.strftime("%Y-%m-%d %H:%M:%S")

    def get_absolute_url(self):
        return reverse('blog:blog_detail', args=[self.id])

    def total_likes(self):
        return self.likes.count()
    
    

blog/views.py
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Blog
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.detail import DetailView
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.db.models import Q

@login_required
def blog_list(request):
    query = request.GET.get('q', '')
    if query:
        blogs = Blog.objects.filter(
            Q(text__icontains=query) | Q(author__username__icontains=query)
        ).distinct()
    else:
        blogs = Blog.objects.all()
    return render(request, 'blog/list.html', {'blogs': blogs, 'query': query})

class BlogDetailView(LoginRequiredMixin, DetailView):
    model = Blog
    fields = ['photo','text']
    template_name = 'blog/detail.html'

class BlogUploadView(LoginRequiredMixin, CreateView):
    model = Blog
    fields = ['photo', 'text']
    template_name = 'blog/upload.html'

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id

        if form.is_valid():
            form.instance.save()
            return redirect('blog:blog_list')
        else: 
            return self.render_to_response({'form':form})
        
class BlogDeleteView(LoginRequiredMixin, DeleteView):
    model = Blog
    success_url = '/'
    template_name = 'blog/delete.html'


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = ['photo','text']
    template_name = 'blog/update.html'

# 좋아요 기능    
@login_required
def blog_like(request, pk):
    blog = get_object_or_404(Blog, id=pk)
    if blog.likes.filter(id=request.user.id).exists():
        blog.likes.remove(request.user)
        liked = False
    else:
        blog.likes.add(request.user)
        liked = True
    return JsonResponse({'total_likes': blog.likes.count(), 'liked': liked})

blog/templates/blog/delete.html
{% extends 'base.html' %}

{% block title %}- Delete{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8 panel panel-default">
            <div class="alert alert-info">
                Do you want to delete {{object}}?
            </div>
            <form action="" method="post">
                {{form.as_p}}
                {% csrf_token %}
                <input type="submit" class="btn btn-danger" value="삭제하기">
            </form>
        </div>
        <div class="col-md-2"></div>
    </div>
{% endblock %}

blog/templates/blog/detail.html
{% extends 'base.html' %}

{% block title %}
    {{object.text|truncatechars:10}}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8 panel panel-default">
            <p><img src="{{object.photo.url}}" style="width:100%;"></p>
            <button type="button" class="btn btn-outline-primary btn-sm">
                {{object.author.username}}</button>
            <p>{{object.text|linebreaksbr}}</p>

            <a href="{% url 'blog:blog_delete' pk=object.id %}" class="btn btn-outline-danger btn-sm float-right">
                삭제하기</a>
            <a href="{% url 'blog:blog_update' pk=object.id %}" class="btn btn-outline-success btn-sm float-right">
                업데이트</a>
        </div>
        <div class="col-md-2"></div>
    </div>
    
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8 panel panel-default">
            {% load disqus_tags %}
            {% disqus_show_comments %}
        </div>
        <div class="col-md-2"></div>
    </div>
{% endblock %}

blog/templates/blog/list.html
{% extends 'base.html' %}

{% block title %} - List {% endblock %}

{% block content %}
    <div class="row mb-3"> 
        <div class="col-md-12 text-right"> 
        <!-- 검색기능 -->
        <form method="GET" action="{% url 'blog:blog_list' %}">
            <div class="form-group">
                <input type="text" name="q" class="form-control" placeholder="Search..." value="{{ query }}">
            </div>
            <button type="submit" class="btn btn-primary">Search</button>
        </form>
        <!-- 검색기능 끝 -->
        <hr>
            <a href="{% url 'blog:blog_upload' %}" class="btn btn-primary">글쓰기</a>
        </div>
    </div>

    {% for post in blogs %}
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8 panel panel-default">
            <p><img src="{{ post.photo.url }}" style="width:100%;"></p>
            <button type="button" class="btn btn-xs btn-info">
                {{ post.author.username }}
            </button>
            <p>{{ post.text|linebreaksbr }}</p>
            <p class="text-right">
                <div>
                    <a href="javascript:void(0)" data-url="{% url 'blog:blog_like' post.id %}" class="like-btn">❤️ <span class="like-count">{{ post.likes.count }}</span></a>
                </div>
                <a href="{% url 'blog:blog_detail' pk=post.id %}" class="btn btn-xs btn-success">댓글달기</a>
            </p>
        </div>
        <div class="col-md-2"></div>
    </div>
    {% endfor %}

    <!-- 좋아요기능 -->
    <script>
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        
        document.addEventListener('DOMContentLoaded', function() {
            const likeButtons = document.querySelectorAll('.like-btn');
            likeButtons.forEach(button => {
                button.addEventListener('click', function(e) {
                    const url = this.dataset.url;
                    fetch(url, {
                        method: 'POST',
                        headers: {
                            'X-Requested-With': 'XMLHttpRequest',
                            'Content-Type': 'application/json',
                            'X-CSRFToken': getCookie('csrftoken'),
                        },
                    })
                    .then(response => response.json())
                    .then(data => {
                        const likeCountSpan = this.querySelector('.like-count');
                        likeCountSpan.textContent = data.total_likes;
                        this.innerHTML = data.liked ? '❤️ ' : '🤍 ';
                        this.appendChild(likeCountSpan);
                    })
                    .catch(error => console.error('Error:', error));
                });
            });
        });
        </script>
    <!-- 좋아요기능 끝 -->
{% endblock %}

blog/templates/blog/update.html
{% extends 'base.html' %}

{% block title %}- Update{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8 panel panel-default">
            <form action="" method="post" enctype="multipart/form-data">
                {{form.as_p}}
                {% csrf_token %}
                <input type="submit" class="btn btn-primary" value="업데이트">
            </form>
        </div>
        <div class="col-md-2"></div>
    </div>
{% endblock %}

blog/templates/blog/upload.html
{% extends 'base.html' %}

{% block title %}- Upload{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8 panel panel-default">
            <form action="" method="post" enctype="multipart/form-data">
                {{form.as_p}}
                {% csrf_token %}
                <input type="submit" class="btn btn-primary" value="업로드">
            </form>
        </div>
        <div class="col-md-2"></div>
    </div>
{% endblock %}